name: workshops
description: Workshops
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  accel_key:
    path: packages/accel_key
  async_value:
    path: packages/async_value
  collection: ^1.15.0
  command_palette:
    git:
      ref: scroll-to-highlighted-action
      url: https://github.com/jpnurmi/command_palette.git
  command_store:
    path: packages/command_store
  context_menu:
    path: packages/context_menu
  data_size: ^0.2.0
  fake_async: ^1.3.1
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_staggered_grid_view: ^0.6.1
  freezed_annotation: ^2.0.3
  handy_window: ^0.1.8
  intl: ^0.17.0
  json_annotation: ^4.5.0
  lxd:
    git:
      url: https://github.com/jpnurmi/lxd.dart
      ref: 9799464c4488f52203407169baca963f88f0e349
  lxd_service:
    path: packages/lxd_service
  lxd_test:
    path: packages/lxd_test
  lxd_x:
    path: packages/lxd_x
  meta: ^1.7.0
  movable_tabs:
    path: packages/movable_tabs
  nested_split_view:
    path: packages/nested_split_view
  os_logo:
    path: packages/os_logo
  osarch:
    path: packages/osarch
  petname:
    path: packages/petname
  provider: ^6.0.3
  safe_change_notifier: ^0.2.0
  settings_store:
    path: packages/settings_store
  shared_preferences: ^2.0.15
  simplestreams:
    path: packages/simplestreams
  substring_highlight: ^1.0.33
  terminal_view:
    path: packages/terminal_view
  ubuntu_localizations: ^0.0.2
  ubuntu_logger:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_logger
  ubuntu_service:
    git:
      url: https://github.com/ubuntu-flutter-community/ubuntu_service.git
  ubuntu_widgets:
    git:
      url: https://github.com/canonical/ubuntu-flutter-plugins.git
      path: packages/ubuntu_widgets
  window_title_bar:
    path: packages/window_title_bar
  wizard_router: ^0.9.0
  yaru: ^0.4.1
  yaru_icons: ^0.2.6
  yaru_widgets: ^2.0.0-0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mockito: 5.3.2

flutter:
  generate: true
  uses-material-design: true
  assets:
    - assets/

dependency_overrides:
  gsettings:
    git:
      # https://github.com/canonical/gsettings.dart/pull/47
      url: https://github.com/canonical/gsettings.dart
