name: os_logo
description: OS logo
publish_to: 'none'

environment:
  sdk: ">=2.17.0 <3.0.0"
  flutter: ">=3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_svg: ^1.1.0

dev_dependencies:
  build_runner: ^2.1.11
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter
  mockito: 5.3.2

flutter:
  assets:
    - assets/
