name: jsettings_example
publish_to: 'none'

environment:
  sdk: '>=3.5.0 <4.0.0'

dependencies:
  collection: ^1.16.0
  flutter:
    sdk: flutter
  flutter_jsettings:
    path: ../
  path: ^1.8.2
  provider: ^6.0.4
  ubuntu_service: ^0.2.0
  xdg_directories: ^1.0.0
  yaru: ^6.0.0

dev_dependencies:
  flutter_lints: ^2.0.0

flutter:
  assets:
    - assets/
  uses-material-design: true
