name: simplestreams
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  equatable: ^2.0.5
  intl: ^0.17.0
  json_annotation: ^4.5.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.11
  json_serializable: ^6.2.0
  mockito: 5.3.2
  test: ^1.21.1
