name: simplestreams
publish_to: 'none'

environment:
  sdk: '>=2.17.0 <3.0.0'

dependencies:
  freezed_annotation: ^2.0.3
  intl: ^0.17.0
  json_annotation: ^4.5.0
  meta: ^1.7.0

dev_dependencies:
  build_runner: ^2.1.11
  freezed: ^2.0.3+1
  json_serializable: ^6.2.0
  mockito: 5.3.0
  test: ^1.21.1
